version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=HospitalDB
      - MYSQL_USER=hamza
      - MYSQL_PASSWORD=hamza
    ports:
      - 3304:3306
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 9001:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql

#version: '3'
#
#services:
#  docker-mysql:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=
#      - MYSQL_DATABASE=HospitalDB
#      - MYSQL_USER=hamza
#      - MYSQL_PASSWORD=hamza
#    ports:
#      - 3307:3306
#
#  springboot-docker-container:
#    image: springboot-docker-container
#    ports:
#      - 8091:8091
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/HospitalDB?createDatabaseIfNotExist=true
#    depends_on:
#      - docker-mysql

#
#version: "3.8"
#services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: .
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#volumes:
#  db: